networks:
  dev:

services:
  backend:
    container_name: "backend"
    build: BackendKotitk/
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      HOST: ${HOST}
    env_file:
      - .env
    networks:
      - dev

  frontend:
    container_name: "frontend"
    build: FrontendKotik/
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - dev

  db:
    container_name: "db"
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - dev 

volumes:
  db_data: